typing_indicators = [
    "Processing your request, please wait...",
    "Hmm, that's an interesting query...",
    "Let me think about that for a moment...",
    "I'm on it, just a moment...",
    "Running computations, stand by...",
    "Engaging my AI circuits...",
    "Bear with me while I fetch that information...",
    "Just a moment while I ponder that...",
    "You've piqued my curiosity, let me think...",
    "I'm diving into my knowledge base...",
    "Engaging my algorithms...",
    "This requires some thought, hold on...",
    "Hmm, let me sift through my data...",
    "Interesting, let me work on that...",
    "I'm running through my information...",
    "One moment, I'm putting my processors to work...",
    "Just a second, I'm thinking...",
    "I'm gathering the information you need...",
    "I'm reaching into my extensive knowledge...",
    "Processing... I'll have your answer soon..."
]

image_analysis_messages = [
    "Let's see, I'm analyzing this image...",
    "Taking a closer look at this picture...",
    "This is an interesting picture, let me examine it closely...",
    "Hold on, processing the pixels...",
    "Engaging my AI vision capabilities...",
    "Let me interpret this image for you...",
    "I'm scrutinizing the image...",
    "Hang on, I'm examining the picture...",
    "This image is fascinating, let me analyze it...",
    "I'm processing this image, hold on...",
    "Activating my AI vision...",
    "Let's see what's in this picture...",
    "Hmm, let me look at this picture...",
    "Analyzing the image, hold tight...",
    "I'm looking at the image, one moment...",
    "Let me study the details of this image...",
    "Running image analysis...",
    "I'm diving into the details of this image...",
    "I'm taking a good look at this image...",
    "Let me process this interesting image..."
]

image_generation_messages = [
    "Generating an image of {}...",
    "Crafting a visual representation of {}...",
    "Piecing together pixels for {}...",
    "Constructing a depiction of {}...",
    "Spinning up an image of {}...",
    "Drawing up the details for {}...",
    "Painting a digital picture of {}...",
    "Assembling the imagery for {}...",
    "Building a visual of {} from scratch...",
    "Stitching together an image of {}...",
    "Forming the visual data for {}...",
    "Creating a canvas for {}...",
    "Molding the pixels to illustrate {}...",
    "Weaving a visual tapestry for {}...",
    "Breathing life into the image of {}...",
    "Turning codes into a canvas for {}...",
    "Sketching the digital outlines of {}...",
    "Bringing {} to visual life...",
    "Designing a vibrant visual of {}...",
    "Transforming data into the depiction of {}..."
]

google_search_messages = [
    'Searching for "{}"...',
    'Looking up "{}", please wait...',
    'Retrieving "{}", hold on...',
    'Finding information on "{}"...',
    'Querying for "{}", stand by...',
    'Gathering results for "{}"...',
    'Scanning the web for "{}"...',
    'Processing query for "{}"...',
    'Sourcing data on "{}"...',
    'Executing search for "{}"...',
    'Initiating lookup for "{}"...',
    'Compiling information on "{}"...',
    'Collecting data for "{}"...',
    'Exploring the web for "{}"...',
    'Running query on "{}"...',
    'Searching databases for "{}"...',
    'Filtering results for "{}"...',
    'Checking available information for "{}"...',
    'Analyzing web data for "{}"...',
    'Performing search on "{}"...'
]

scrape_web_page_messages = [
    'Retrieving data from {}...',
    'Scanning content on {}...',
    'Collecting information from {}...',
    'Analyzing web page {}...',
    'Fetching details from {}...',
    'Examining site {}...',
    'Accessing content on {}...',
    'Reading data from {}...',
    'Querying information on {}...',
    'Exploring {} for data...',
    'Pulling content from {}...',
    'Scraping details off {}...',
    'Crawling through {}...',
    'Gathering text from {}...',
    'Processing page {}...',
    'Extracting data from {}...',
    'Navigating through {}...',
    'Harvesting information from {}...',
    'Inspecting elements on {}...',
    'Collecting assets from {}...'
]

status_list = [
    "with the mainframe...",
    "in the data sandbox...",
    "catch with binary codes...",
    "hide and seek in servers...",
    "tunes on the algorithmic strings...",
    "hopscotch on the cloud...",
    "chess with AI moves...",
    "cards in the digital deck...",
    "tricks with command prompts...",
    "puzzles with encrypted pieces...",
    "drums with button clicks...",
    "paintball in the pixel field...",
    "dice with random number generators...",
    "tag in the cyber arena...",
    "tunes on the digital keyboard...",
    "fetch with data packets...",
    "marbles with data orbs...",
    "dominoes with code blocks...",
    "jenga with server racks...",
    "race with data streams..."
]